CREATE DATABASE IF NOT EXISTS dy_db;
CREATE DATABASE IF NOT EXISTS pm_workflow;
CREATE DATABASE IF NOT EXISTS pm_resource;

USE pm_resource;

CREATE TABLE IF NOT EXISTS project (
  id          BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id     BIGINT       NOT NULL,
  name        VARCHAR(200) NOT NULL,
  description TEXT,
  created_at  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX idx_project_user_id (user_id)
);
