server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: dy-auth
              uri: lb://DY-AUTH
              predicates:
                - Path=/api/auth/**
            - id: dy-auth-oauth2
              uri: lb://DY-AUTH
              predicates:
                - Path=/oauth2/**
            - id: dy-auth-login-oauth2
              uri: lb://DY-AUTH
              predicates:
                - Path=/login/oauth2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
